/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.atividadebanco;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/**
 *
 * @author italodell
 */
public class Criar extends javax.swing.JDialog {

    /**
     * Creates new form Criar
     */
    public Criar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Senha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Tipoconta = new javax.swing.JComboBox<>();
        Curso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Criar = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Criação de conta");

        jLabel2.setText("Nome do titular");

        jLabel3.setText("Senha");

        jLabel4.setText("Tipo de conta");

        Tipoconta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Conta Especial", "Conta Universitaria", "Conta Poupanca" }));

        jLabel5.setText("Curso");

        Criar.setText("Criar Conta");
        Criar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarActionPerformed(evt);
            }
        });

        Voltar.setText("Voltar ao Menu");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Curso, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Nome)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Criar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Voltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(Tipoconta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel1)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tipoconta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addComponent(Curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Criar)
                    .addComponent(Voltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    ArrayList<Contas> comum = new ArrayList<>();
    ArrayList<Poupanca> poupanca = new ArrayList<>();

    public void setComum(ArrayList<Contas> comum) {
        this.comum = comum;
    }

    public void setPoupanca(ArrayList<Poupanca> poupanca) {
        this.poupanca = poupanca;
    }

    public void setEspecial(ArrayList<Especial> especial) {
        this.especial = especial;
    }

    public void setUniversitaria(ArrayList<Universitaria> universitaria) {
        this.universitaria = universitaria;
    }
    ArrayList<Especial> especial = new ArrayList<>();
    ArrayList<Universitaria> universitaria = new ArrayList<>();
    
    private void CriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarActionPerformed
        // TODO add your handling code here:
        if(Nome.getText().trim().isEmpty() || Senha.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!", "Falha!", INFORMATION_MESSAGE);
        }else{
            String tipo = (String) Tipoconta.getSelectedItem();

            if(tipo == "Conta Especial"){
                int i = especial.size();
                Especial c1 = new Especial(i+1,Nome.getText(),Integer.parseInt(Senha.getText()), 2);
                especial.add(c1);
                JOptionPane.showMessageDialog(null, "Operacao foi um sucesso!\nSua ID:"+ (i+1)+"\n"+"Sua senha: "+c1.getSenha(), "Concluido!", INFORMATION_MESSAGE);
            
            }
            if(tipo == "Conta Poupanca"){
                int i = poupanca.size();
                Poupanca c1 = new Poupanca(i+1,Nome.getText(),Integer.parseInt(Senha.getText()), 3);
                poupanca.add(c1);
                JOptionPane.showMessageDialog(null, "Operacao foi um sucesso!\nSua ID:"+ (i+1)+"\n"+"Sua senha: "+c1.getSenha(), "Concluido!", INFORMATION_MESSAGE);
            }
            if(tipo == "Conta Universitaria"){
                int i = universitaria.size();
                if(Curso.getText().trim().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Preencha todos os campos!", "Falha!", INFORMATION_MESSAGE);
                }else{
                Universitaria c1 = new Universitaria(Curso.getText(),i+1,Nome.getText(),Integer.parseInt(Senha.getText()), 4);
                universitaria.add(c1);
                JOptionPane.showMessageDialog(null, "Operacao foi um sucesso!\nSua ID:"+ (i+1) +"\n"+"Sua senha: "+c1.getSenha(), "Concluido!", INFORMATION_MESSAGE);
                }
            }
        
        }
            
        
    }//GEN-LAST:event_CriarActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Criar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Criar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Criar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Criar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Criar dialog = new Criar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Criar;
    private javax.swing.JTextField Curso;
    private javax.swing.JTextField Nome;
    private javax.swing.JTextField Senha;
    private javax.swing.JComboBox<String> Tipoconta;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
